networks:
  pulsar:
    driver: bridge
    
services:
  pulsar:
    image: "apachepulsar/pulsar:2.6.2"
    restart: unless-stopped
    command: bin/pulsar standalone
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - ./pulsar/data:/pulsar/data
    ports:
      - "6650:6650"
      - "8080:8080"
    networks:
      - pulsar
  
  pulsar-manager:
    image: "apachepulsar/pulsar-manager:v0.2.0"
    restart: unless-stopped
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      - pulsar
