#  docker-compose -f .docker/docker-compose-seq.yml -p seq up -d
#  docker-compose -f .docker/docker-compose-seq.yml -p seq down

networks:
  seq:
    driver: bridge
services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5341:80"
    shm_size: 128mb
    environment:
      - ACCEPT_EULA=Y
      - SEQ__HOST=seq
      - SEQ__PORT=5341
#      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
#      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    volumes:
      - ~/.docker-data/seq/data:/data
    restart: unless-stopped