#  docker-compose -f .docker/docker-compose-all-consumers.yml -p topica_consumers up -d
#  docker-compose -f .docker/docker-compose-all-consumers.yml -p topica_consumers down

services:
  aws.queue.consumer.host:
    build:
      context: ../src
      dockerfile: Aws.Queue.Consumer.Host/Dockerfile
    environment:
      - SOME_VAR=variable

  aws.topic.consumer.host:
    build:
      context: ../src
      dockerfile: Aws.Topic.Consumer.Host/Dockerfile
    environment:
      - SOME_VAR=variable
  
  azure.servicebus.topic.consumer.host:
    build:
      context: ../src
      dockerfile: Azure.ServiceBus.Topic.Consumer.Host/Dockerfile
    environment:
      - SOME_VAR=variable

  kafka.topic.consumer.host:
    build:
      context: ../src
      dockerfile: Kafka.Topic.Consumer.Host/Dockerfile
    environment:
      - SOME_VAR=variable
  
  pulsar.topic.consumer.host:
    build:
      context: ../src
      dockerfile: Pulsar.Topic.Consumer.Host/Dockerfile
    environment:
      - SOME_VAR=variable
  
  rabbitmq.queue.consumer.host:
    build:
      context: ../src
      dockerfile: RabbitMq.Queue.Consumer.Host/Dockerfile
    environment:
      - SOME_VAR=variable
  
  rabbitmq.topic.consumer.host:
    build:
      context: ../src
      dockerfile: RabbitMq.Topic.Consumer.Host/Dockerfile
    environment:
      - SOME_VAR=variable
