name: Docker Build & Push

on:
  push:
    branches: [ dev ]
    paths:
      - ".github/workflows/cd_docker_build_push.yml"
      - "src/**"
  
  workflow_dispatch:

jobs:
  build-docker-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits, so we can generate version off of tags/commit sha...
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t rehmanab/topica.web:${{ github.run_number }} ./src/Topica.Web

      - name: Push Docker image
        run: |
          docker push rehmanab/topica.web:${{ github.run_number }}
